# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "damp-tooth-c648"
main = "src/worker.js"
compatibility_date = "2025-12-30"

# [vars]
# KEY = "value"

# npx wrangler secret put <SECRET_KEY>
