# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "damp-tooth-c648"
main = "src/worker.js"
compatibility_date = "2025-12-30"

workers_dev = true
preview_urls = false

# [vars]
# KEY = "value"

# npx wrangler secret put <SECRET_KEY>

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
