# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "damp-tooth-c648"
main = "src/worker.js"
compatibility_date = "2025-12-30"

workers_dev = true
preview_urls = false

[vars]
# DEBUG = true
FORWARD_EXCLUDE_SENDER = true
SHOW_ATTACHMENTS = true
# SHOW_RAW_BODY = true

# Store secrets in .env file and set them using the command below:
# npx wrangler secret put <SECRET_KEY>

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true
